# Generated by Django 4.2.3 on 2023-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name='Адрес электронной почты')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Изображение')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
